# Generated by Django 6.1 on 2026-08-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_rbac_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitelink',
            options={'ordering': ['-created_at'], 'verbose_name': 'لینک دعوت', 'verbose_name_plural': 'لینک\u200cهای دعوت'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['codename'], 'verbose_name': 'دسترسی', 'verbose_name_plural': 'دسترسی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'دسترسی نقش', 'verbose_name_plural': 'دسترسی\u200cهای نقش\u200cها'},
        ),
    ]
