# Generated by Django 6.1 on 2026-08-15 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_persian_permission_role_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitelink',
            options={'ordering': ['-created_at'], 'verbose_name': 'لینک دعوت', 'verbose_name_plural': 'لینک\u200cهای دعوت'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['codename'], 'verbose_name': 'دسترسی', 'verbose_name_plural': 'دسترسی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'دسترسی نقش', 'verbose_name_plural': 'دسترسی\u200cهای نقش\u200cها'},
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ایجاد'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='used_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP استفاده'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.SlugField(max_length=100, unique=True, verbose_name='کد دسترسی'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام دسترسی'),
        ),
        migrations.AlterField(
            model_name='role',
            name='codename',
            field=models.SlugField(unique=True, verbose_name='کد نقش'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='users.RolePermission', to='users.permission', verbose_name='دسترسی\u200cها'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_role_set', to='users.permission', verbose_name='دسترسی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='تعیین می\u200cکند که این کاربر همه دسترسی\u200cها را بدون بررسی جداگانه دارد.', verbose_name='ابرکاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP ورود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان قفل حساب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='نیاز به تغییر رمز عبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص داده شده توسط'),
        ),
    ]
