# Generated by Django 6.1 on 2026-08-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_invitelink_created_by_and_more'),
        ('users', '0004_alter_invitelink_options_alter_permission_options_and_more'),
    ]

    operations = [
    ]
