# Generated by Django 6.1 on 2026-08-25 11:13

import django.core.validators
import django.db.models.deletion
import tasbih.related_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_merge_20260809_2008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasbih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='نام')),
                ('bead_material', models.CharField(blank=True, default='', max_length=100, verbose_name='جنس دانه')),
                ('bead_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد دانه')),
                ('bead_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='اندازه دانه (میلی\u200cمتر)')),
                ('total_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='طول کل (سانتی\u200cمتر)')),
                ('tassel_material', models.CharField(blank=True, default='', max_length=100, verbose_name='جنس منگوله')),
                ('spacer_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد جداکننده')),
                ('origin_mine', models.CharField(blank=True, default='', max_length=150, verbose_name='معدن / منبع')),
                ('color', models.CharField(blank=True, default='', max_length=80, verbose_name='رنگ')),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن (گرم)')),
                ('is_natural', models.BooleanField(default=True, verbose_name='طبیعی')),
                ('craftsmanship', models.CharField(blank=True, default='', max_length=150, verbose_name='سبک ساخت')),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='کشور')),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='سال')),
                ('historical_period', models.CharField(blank=True, default='', max_length=150, verbose_name='دوره تاریخی')),
                ('catalog_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='شماره کاتالوگ')),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'عالی'), ('good', 'خوب'), ('fair', 'متوسط'), ('poor', 'ضعیف'), ('other', 'سایر')], default='', max_length=20, verbose_name='وضعیت')),
                ('authenticity', models.CharField(choices=[('authentic', 'اصلی'), ('suspect', 'مشکوک'), ('counterfeit', 'جعلی'), ('unverified', 'تأییدنشده'), ('unknown', 'نامشخص')], db_index=True, default='unknown', max_length=20, verbose_name='اصالت')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('purchase_location', models.CharField(blank=True, default='', max_length=255, verbose_name='محل خرید')),
                ('seller', models.CharField(blank=True, default='', max_length=150, verbose_name='فروشنده')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید')),
                ('purchase_currency', models.CharField(blank=True, choices=[('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا'), ('EUR', 'یورو'), ('GBP', 'پوند'), ('TRY', 'لیر ترکیه'), ('AED', 'درهم امارات'), ('OTHER', 'سایر')], default='', max_length=10, verbose_name='واحد پول خرید')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ارزش فعلی')),
                ('last_valuation_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین ارزیابی')),
                ('cabinet_number', models.CharField(blank=True, default='', max_length=50, verbose_name='کمد')),
                ('drawer_number', models.CharField(blank=True, default='', max_length=50, verbose_name='کشو')),
                ('box_number', models.CharField(blank=True, default='', max_length=50, verbose_name='جعبه')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasbih_items', to='categories.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'تسبیح',
                'verbose_name_plural': 'تسبیح\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TasbihImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tasbih.related_models.tasbih_image_upload_to, verbose_name='تصویر')),
                ('image_type', models.CharField(choices=[('front', 'رو'), ('back', 'پشت'), ('detail', 'جزئیات'), ('certificate', 'گواهی'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع تصویر')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='تصویر اصلی')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='نام فایل اصلی')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasbih.tasbih', verbose_name='تسبیح')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_tasbih_images', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'تصویر تسبیح',
                'verbose_name_plural': 'تصاویر تسبیح\u200cها',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TasbihPurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='محل خرید')),
                ('seller', models.CharField(blank=True, default='', max_length=150, verbose_name='فروشنده')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('currency', models.CharField(blank=True, default='', max_length=10, verbose_name='واحد پول')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasbih_purchases', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='tasbih.tasbih', verbose_name='تسبیح')),
            ],
            options={
                'verbose_name': 'سابقه خرید تسبیح',
                'verbose_name_plural': 'سوابق خرید تسبیح\u200cها',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TasbihValuationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ارزش')),
                ('currency', models.CharField(blank=True, default='', max_length=10, verbose_name='واحد پول')),
                ('valuation_date', models.DateField(verbose_name='تاریخ قیمت\u200cگذاری')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='منبع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasbih_valuations', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_records', to='tasbih.tasbih', verbose_name='تسبیح')),
            ],
            options={
                'verbose_name': 'سابقه ارزش\u200cگذاری تسبیح',
                'verbose_name_plural': 'سوابق ارزش\u200cگذاری تسبیح\u200cها',
                'ordering': ['-valuation_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='tasbih',
            index=models.Index(fields=['country', 'year'], name='tasbih_tasb_country_3dad99_idx'),
        ),
        migrations.AddIndex(
            model_name='tasbih',
            index=models.Index(fields=['catalog_number'], name='tasbih_tasb_catalog_bca943_idx'),
        ),
        migrations.AddIndex(
            model_name='tasbih',
            index=models.Index(fields=['-created_at'], name='tasbih_tasb_created_754de6_idx'),
        ),
    ]
