# Generated by Django 6.1 on 2026-08-17 08:15

import coins.related_models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_merge_20260809_2008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='نام')),
                ('item_type', models.CharField(choices=[('coin', 'سکه'), ('banknote', 'اسکناس'), ('token', 'توکن / ژتون'), ('bullion', 'شمش / فلز گران\u200cبها'), ('other', 'سایر')], db_index=True, default='coin', max_length=20, verbose_name='نوع قلم')),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='کشور')),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='سال (میلادی)')),
                ('year_hijri', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال (هجری / شمسی)')),
                ('historical_period', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='دوره تاریخی')),
                ('reign_or_ruler', models.CharField(blank=True, default='', max_length=150, verbose_name='حاکم / سلسله')),
                ('face_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ارزش اسمی')),
                ('denomination', models.CharField(blank=True, default='', max_length=100, verbose_name='واحد اسمی (ریال، قران، ...)')),
                ('currency_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام ارز / واحد پول')),
                ('material', models.CharField(blank=True, default='', max_length=100, verbose_name='جنس / آلیاژ')),
                ('purity', models.DecimalField(blank=True, decimal_places=3, help_text='عیار به درصد، مثلاً 90 برای نقره ۹۰۰', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='عیار (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=4, help_text='گرم', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن (گرم)')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, help_text='میلی\u200cمتر', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قطر (میلی\u200cمتر)')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ضخامت (میلی\u200cمتر)')),
                ('shape', models.CharField(blank=True, default='', max_length=80, verbose_name='شکل')),
                ('edge', models.CharField(blank=True, default='', max_length=120, verbose_name='لبه')),
                ('color', models.CharField(blank=True, default='', max_length=80, verbose_name='رنگ')),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='شماره سریال')),
                ('series', models.CharField(blank=True, default='', max_length=120, verbose_name='سری / انتشار')),
                ('signature', models.CharField(blank=True, default='', max_length=200, verbose_name='امضا / مقام مسئول')),
                ('printer', models.CharField(blank=True, default='', max_length=150, verbose_name='چاپخانه')),
                ('mint', models.CharField(blank=True, default='', max_length=150, verbose_name='ضرابخانه')),
                ('maker', models.CharField(blank=True, default='', max_length=150, verbose_name='سازنده')),
                ('mintage', models.PositiveIntegerField(blank=True, null=True, verbose_name='تیراژ')),
                ('catalog_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='شماره کاتالوگ')),
                ('quality', models.CharField(blank=True, choices=[('UNC', 'Uncirculated (UNC)'), ('AU', 'About Uncirculated (AU)'), ('XF', 'Extremely Fine (XF)'), ('VF', 'Very Fine (VF)'), ('F', 'Fine (F)'), ('VG', 'Very Good (VG)'), ('G', 'Good (G)'), ('AG', 'About Good (AG)'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('OTHER', 'Other')], db_index=True, default='', max_length=10, verbose_name='کیفیت')),
                ('preservation_condition', models.CharField(blank=True, default='', max_length=255, verbose_name='وضعیت نگهداری')),
                ('authenticity', models.CharField(choices=[('authentic', 'اصلی'), ('suspect', 'مشکوک'), ('counterfeit', 'جعلی'), ('unverified', 'تأییدنشده'), ('unknown', 'نامشخص')], db_index=True, default='unknown', max_length=20, verbose_name='اصالت')),
                ('is_proof', models.BooleanField(default=False, verbose_name='نسخه پروف (Proof)')),
                ('is_commemorative', models.BooleanField(default=False, verbose_name='یادبودی')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('purchase_location', models.CharField(blank=True, default='', max_length=255, verbose_name='محل خرید')),
                ('seller', models.CharField(blank=True, default='', max_length=150, verbose_name='فروشنده')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید')),
                ('purchase_currency', models.CharField(blank=True, choices=[('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا'), ('EUR', 'یورو'), ('GBP', 'پوند'), ('TRY', 'لیر ترکیه'), ('AED', 'درهم امارات'), ('OTHER', 'سایر')], default='', max_length=10, verbose_name='واحد پول خرید')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ارزش فعلی')),
                ('last_valuation_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین ارزیابی')),
                ('cabinet_number', models.CharField(blank=True, default='', max_length=50, verbose_name='کمد')),
                ('drawer_number', models.CharField(blank=True, default='', max_length=50, verbose_name='کشو')),
                ('box_number', models.CharField(blank=True, default='', max_length=50, verbose_name='جعبه')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coins', to='categories.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'سکه / پول',
                'verbose_name_plural': 'سکه\u200cها و پول\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=coins.related_models.coin_image_upload_to, verbose_name='تصویر')),
                ('image_type', models.CharField(choices=[('front', 'رو'), ('back', 'پشت'), ('edge', 'لبه'), ('detail', 'جزئیات'), ('certificate', 'گواهی'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع تصویر')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='تصویر اصلی')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='نام فایل اصلی')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coins.coin', verbose_name='سکه/پول')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_coin_images', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'تصویر سکه/پول',
                'verbose_name_plural': 'تصاویر سکه و پول',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['country', 'year'], name='coins_coin_country_122dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['item_type', 'country'], name='coins_coin_item_ty_fdd0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['catalog_number'], name='coins_coin_catalog_3951ee_idx'),
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['quality'], name='coins_coin_quality_3f1a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['-created_at'], name='coins_coin_created_41af0b_idx'),
        ),
    ]
