# Generated by Django 6.1 on 2026-08-17 07:56

import coins.related_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=coins.related_models.coin_image_upload_to, verbose_name='تصویر')),
                ('image_type', models.CharField(choices=[('front', 'رو'), ('back', 'پشت'), ('edge', 'لبه'), ('detail', 'جزئیات'), ('certificate', 'گواهی'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع تصویر')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='تصویر اصلی')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='نام فایل اصلی')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coins.coin', verbose_name='سکه/پول')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_coin_images', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'تصویر سکه/پول',
                'verbose_name_plural': 'تصاویر سکه و پول',
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
