# Generated by Django 6.1 on 2026-08-25 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_purchase_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='purity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='عیار به درصد', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='عیار (%)'),
        ),
    ]
