# Generated by Django 6.1 on 2026-08-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options'),
        ('categories', '0003_alter_category_options_alter_category_created_at_and_more'),
    ]

    operations = [
    ]
