"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent

_INSECURE_DEV_SECRET = 'django-insecure-dev-only-change-me-in-production'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _INSECURE_DEV_SECRET)

DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes')

if not DEBUG and SECRET_KEY in ('', _INSECURE_DEV_SECRET):
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set to a strong unique value when DEBUG is False.'
    )

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',

    'users',
    'categories',
    'medals',
    'reports',
    'coins',
    'banknotes',
    # Enable after full module install:
    # 'seals',
    # 'tasbih',
    # 'rings',
    # 'knives',
    # 'antiques',
    # 'stamps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "config.middleware.APICorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

PASSWORD_MAX_LENGTH = 128

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MEDAL_IMAGE_MAX_BYTES = int(os.environ.get('MEDAL_IMAGE_MAX_BYTES', 10 * 1024 * 1024))
MEDAL_FILE_MAX_BYTES = int(os.environ.get('MEDAL_FILE_MAX_BYTES', 20 * 1024 * 1024))
MEDAL_IMAGE_MAX_COUNT = 10
COLLECTION_IMAGE_MAX_BYTES = int(os.environ.get('COLLECTION_IMAGE_MAX_BYTES', 10 * 1024 * 1024))
COLLECTION_IMAGE_MAX_COUNT = 10

EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.ActiveUserJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'invite_consume': '5/min',
        'invite_create': '20/hour',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

INVITE_LINK_FRONTEND_URL = os.environ.get(
    'INVITE_LINK_FRONTEND_URL',
    'http://localhost:3000',
)

USE_X_FORWARDED_FOR = os.environ.get(
    'DJANGO_USE_X_FORWARDED_FOR', 'false'
).lower() in ('1', 'true', 'yes')

SPECTACULAR_SERVE_PUBLIC = os.environ.get(
    'DJANGO_SPECTACULAR_SERVE_PUBLIC', 'false'
).lower() in ('1', 'true', 'yes')

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
AUTH_USER_MODEL = 'users.User'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Medal Archive API',
    'DESCRIPTION': (
        'API مدیریت آرشیو مدال، سکه و اقلام مجموعه.\n\n'
        '## احراز هویت\n'
        'اکثر endpointها نیاز به JWT دارند:\n'
        '`Authorization: Bearer <access_token>`\n\n'
        '## نقش‌ها\n'
        '- Superuser: همه مجوزها\n'
        '- Admin: کاربران، نقش‌ها، محتوا\n'
        '- Curator: دسته‌بندی و محتوا\n'
        '- Viewer: فقط مشاهده\n\n'
        '## کدهای وضعیت\n'
        '200 موفق | 201 ایجاد | 400 نامعتبر | 401 بدون احراز هویت | 403 بدون مجوز | 404 یافت نشد\n\n'
        '## صفحه‌بندی\n'
        'count, next, previous, results — اندازه صفحه پیش‌فرض ۲۰.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': (
                    'JWT access token. Obtain via POST /api/users/login/, '
                    'then paste: Bearer <access_token>'
                ),
            },
        },
    },
    'SECURITY': [{'BearerAuth': []}],
}
