# Generated by Django 6.1 on 2026-08-08 11:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('occasion', models.CharField(blank=True, default='', max_length=255)),
                ('historical_period', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('maker', models.CharField(blank=True, default='', max_length=150)),
                ('mint_or_manufacturer', models.CharField(blank=True, default='', max_length=150)),
                ('material', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in grams', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, help_text='Diameter in millimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, help_text='Thickness in millimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('shape', models.CharField(blank=True, default='', max_length=80)),
                ('color', models.CharField(blank=True, default='', max_length=80)),
                ('edge', models.CharField(blank=True, default='', max_length=80)),
                ('quality', models.CharField(blank=True, choices=[('UNC', 'Uncirculated (UNC)'), ('AU', 'About Uncirculated (AU)'), ('XF', 'Extremely Fine (XF)'), ('VF', 'Very Fine (VF)'), ('F', 'Fine (F)'), ('VG', 'Very Good (VG)'), ('G', 'Good (G)'), ('AG', 'About Good (AG)'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('OTHER', 'Other')], db_index=True, default='', max_length=10)),
                ('preservation_condition', models.CharField(blank=True, default='', max_length=255)),
                ('authenticity', models.CharField(choices=[('authentic', 'Authentic'), ('suspect', 'Suspect'), ('counterfeit', 'Counterfeit'), ('unverified', 'Unverified'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('catalog_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_location', models.CharField(blank=True, default='', max_length=255)),
                ('seller', models.CharField(blank=True, default='', max_length=150)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_currency', models.CharField(blank=True, choices=[('IRR', 'Iranian Rial'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TRY', 'Turkish Lira'), ('AED', 'UAE Dirham'), ('OTHER', 'Other')], default='', max_length=10)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_valuation_date', models.DateField(blank=True, null=True)),
                ('cabinet_number', models.CharField(blank=True, default='', max_length=50)),
                ('drawer_number', models.CharField(blank=True, default='', max_length=50)),
                ('box_number', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medals', to='categories.category')),
            ],
            options={
                'verbose_name': 'Medal',
                'verbose_name_plural': 'Medals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='medals_meda_name_2bdd78_idx'), models.Index(fields=['country', 'year'], name='medals_meda_country_761349_idx'), models.Index(fields=['catalog_number'], name='medals_meda_catalog_a3e0ba_idx'), models.Index(fields=['quality'], name='medals_meda_quality_5c9f7e_idx'), models.Index(fields=['-created_at'], name='medals_meda_created_b644e9_idx')],
            },
        ),
    ]
