# Generated by Django 6.1 on 2026-08-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medal',
            options={'ordering': ['-created_at'], 'verbose_name': 'مدال', 'verbose_name_plural': 'مدال\u200cها'},
        ),
    ]
