# Generated by Django 6.1 on 2026-08-09 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options_alter_category_created_at_and_more'),
        ('medals', '0002_medal_images_files_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medal',
            options={'ordering': ['-created_at'], 'verbose_name': 'مدال', 'verbose_name_plural': 'مدال\u200cها'},
        ),
        migrations.AlterField(
            model_name='medal',
            name='authenticity',
            field=models.CharField(choices=[('authentic', 'Authentic'), ('suspect', 'Suspect'), ('counterfeit', 'Counterfeit'), ('unverified', 'Unverified'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20, verbose_name='اصالت'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='box_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='شماره باکس'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='cabinet_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='شماره کمد'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='catalog_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='شماره کاتالوگ'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medals', to='categories.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='color',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ارزش روز'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diameter in millimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قطر'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='drawer_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='شماره کشو'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='edge',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='لبه مدال'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='historical_period',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='دوره تاریخی'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='last_valuation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین قیمت\u200cگذاری'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='maker',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='سازنده'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='material',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='جنس'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='mint_or_manufacturer',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='ضرابخانه یا کارخانه سازنده'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='نام مدال'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='occasion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='مناسبت'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='preservation_condition',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='وضعیت نگهداری'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='purchase_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Iranian Rial'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TRY', 'Turkish Lira'), ('AED', 'UAE Dirham'), ('OTHER', 'Other')], default='', max_length=10, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='purchase_location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='محل خرید'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='quality',
            field=models.CharField(blank=True, choices=[('UNC', 'Uncirculated (UNC)'), ('AU', 'About Uncirculated (AU)'), ('XF', 'Extremely Fine (XF)'), ('VF', 'Very Fine (VF)'), ('F', 'Fine (F)'), ('VG', 'Very Good (VG)'), ('G', 'Good (G)'), ('AG', 'About Good (AG)'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('OTHER', 'Other')], db_index=True, default='', max_length=10, verbose_name='کیفیت'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='seller',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='فروشنده'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='shape',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='شکل'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Thickness in millimeters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ضخامت'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in grams', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='سال ساخت'),
        ),
    ]
