# Generated by Django 6.1 on 2026-08-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0002_alter_medal_options'),
        ('medals', '0003_alter_medal_options_alter_medal_authenticity_and_more'),
    ]

    operations = [
    ]
